import { Category, Product } from '@/types/product';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Audio',
    slug: 'audio',
    description: 'Noise-canceling headphones & studio monitors',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    itemCount: 24,
  },
  {
    id: 'cat-2',
    name: 'Workspace',
    slug: 'workspace',
    description: 'Ergonomic desks, lamps & mechanical keyboards',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    itemCount: 18,
  },
  {
    id: 'cat-3',
    name: 'Carry',
    slug: 'carry',
    description: 'Minimalist backpacks, sleeves & travel organizers',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    itemCount: 15,
  },
  {
    id: 'cat-4',
    name: 'Wearables',
    slug: 'wearables',
    description: 'Smart watches, straps & everyday accessories',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    itemCount: 12,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'NOVA Wireless Studio Headphones',
    slug: 'nova-wireless-studio-headphones',
    category: 'Audio',
    price: 299,
    originalPrice: 349,
    rating: 4.9,
    reviewCount: 128,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    badge: 'Best Seller',
    inStock: true,
  },
  {
    id: 'prod-2',
    title: 'Minimalist Aluminum Desk Lamp',
    slug: 'minimalist-aluminum-desk-lamp',
    category: 'Workspace',
    price: 149,
    rating: 4.7,
    reviewCount: 84,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80',
    badge: 'New',
    inStock: true,
  },
  {
    id: 'prod-3',
    title: 'Waterproof Everyday Backpack 20L',
    slug: 'waterproof-everyday-backpack-20l',
    category: 'Carry',
    price: 189,
    originalPrice: 220,
    rating: 4.8,
    reviewCount: 96,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    badge: 'Sale',
    inStock: true,
  },
  {
    id: 'prod-4',
    title: 'Tactile Wireless Mechanical Keyboard',
    slug: 'tactile-wireless-mechanical-keyboard',
    category: 'Workspace',
    price: 169,
    rating: 4.9,
    reviewCount: 210,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    badge: 'Best Seller',
    inStock: true,
  },
];
